global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: demo-api
    metrics_path: /metrics
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']
